test:
    stage: test
    image: pwpon500/libvirt-terraform
    script:
        - apk add --no-cache ruby ruby-dev build-base git
        - ruby -v
        - which ruby
        - gem install bundle --no-ri --no-rdoc
        - bundle install
        - bundle exec rubocop
        - bundle exec rspec

deploy:
    stage: deploy
    image: ruby
    script:
        - gem build jiffy.gemspec
    artifacts:
        paths:
            - jiffy*.gem
